### ISSUE TITLE
Make plugin installable through jenkins plugin manager?

### ISSUE THREAD

**Issue by stmlange** [offa/maintenance-mode#125]
Hello,
thank you for this project! It really sound interesting.

Have you considered to make plugin installable through jenkins plugin manager?
The only option seems to manually build it and then upload it.

Thanks,

**Comment by offa** [comment]
Yes, I'm considering it. It needs some organizational steps to though.

As short-term step I can provide prebuild HPIs for each release.

**Comment by offa** [comment]
Releases have a HPI file attached now.

**Comment by stmlange** [comment]
Thank you :-)

**Comment by gpongelli** [comment]
I'm also interested in having this plugin into plugin manager, FYI I've found some guides [here](https://www.jenkins.io/doc/developer/guides/) on how to publish a plugin.

Thanks.
